name: CI
on: [push, pull_request]
env:
  RAILS_ENV: test
  DATABASE_URL: postgresql://postgres:@localhost/test
  DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL: true
  BUNDLE_WITHOUT: "journald:development:console:mysql2:sqlite"
jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.5
          bundler-cache: true
      - name: Run rubocop
        run: bundle exec rubocop
  test:
    runs-on: ubuntu-latest
    needs: rubocop
    services:
      postgres:
        image: postgres:12.1
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    strategy:
      fail-fast: false
      matrix:
        foreman-core-branch: [develop]
        ruby-version: [2.5, 2.6]
        node-version: [10]
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install build-essential libcurl4-openssl-dev libvirt-dev ruby-libvirt zlib1g-dev libpq-dev
      - uses: actions/checkout@v2
        with:
          repository: theforeman/foreman
          ref: ${{ matrix.foreman-core-branch }}
      - uses: actions/checkout@v2
        with:
          path: foreman_webhooks
      - name: Setup Plugin in Foreman
        run: |
          echo "gem 'foreman_webhooks', path: './foreman_webhooks'" > bundler.d/foreman_webhooks.local.rb
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version:  ${{ matrix.node-version }}
      - name: Setup Plugin
        run: |
          bundle exec rake db:create
          bundle exec rake db:migrate
          npm install
          bundle exec rake webpack:compile
      - name: Run plugin tests
        run: |
          bundle exec rake test:foreman_webhooks
          bundle exec rake test TEST="test/unit/foreman/access_permissions_test.rb"
      - name: Precompile plugin assets
        run: bundle exec rake 'plugin:assets:precompile[foreman_webhooks]'
        env:
          RAILS_ENV: production
